kind: ReplicationController
apiVersion: v1
metadata:
  name: maria1
  labels:
    name: maria1
spec:
  replicas: 1
  selector:
    name: maria1
  template:
    metadata:
      labels:
        name: maria1
    spec:
        containers:
          - name: maria1
            image: inspectormeow/mariadb-galera:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 3306
              - containerPort: 4444
              - containerPort: 4567
              - containerPort: 4568
            env:
              - name: PUBLISH
                value: "3306"
              - name: CLUSTER
                value: galera
              - name: ETCD_PORT
                value: "2379"
              - name: MYSQL_USER
                value: mysql
              - name: MYSQL_PASS
                value: mysql
            volumeMounts:
              - name: maria1-persistent-storage
                mountPath: /var/lib/mysql
        volumes:
          - name: maria1-persistent-storage
            gcePersistentDisk:
              pdName: docker-maria1
              fsType: ext4

