#!/bin/bash
#
# Grant various credentials to mysql before joining cluster
#

mysql -e 'SET wsrep_on=OFF; GRANT select ON *.* TO "haproxy_check"@"%"'
mysql -e 'SET wsrep_on=OFF; GRANT ALL ON *.* TO "{{ .mysql_credentials_change_repUser }}"@"%" IDENTIFIED BY "{{ .mysql_credentials_change_repPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT ALL ON *.* TO "{{ .mysql_credentials_change_repUser }}"@"localhost" IDENTIFIED BY "{{ .mysql_credentials_change_repPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT ALL PRIVILEGES ON *.* TO "{{ .mysql_credentials_change_adminUser }}"@"%" IDENTIFIED BY "{{ .mysql_credentials_change_adminPass }}";'
mysql -e 'SET wsrep_on=OFF; GRANT SUPER ON *.* TO "{{ .mysql_credentials_change_adminUser }}"@"%" WITH GRANT OPTION;'
mysql -e 'FLUSH PRIVILEGES;'

exit 0
